name: pre-cd
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Document Version'
        required: true
        default: 'main'
# 3个功能, 
# 1. 每次发布 main 更新到 dev 文档
# 2. 发布指定版本, 和下面有点不同,就是设置 default
# 3. 更新历史版本
# 这些操作当然本地都可以完成, 主要是打包镜像功能

# 搞个下拉, 选择其他分支就是更新历史, 选择 main 就是 dev. 如果填入 input, 则是新增

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.version }} # 可以指定分支 checkout, 但不允许直接修改 gh-pages
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Intialiaze Python Env
        run: |
          git rev-parse --abbrev-ref HEAD
          pip install -r requirements.txt

      - name: Mike Dev Version Snapshot
        if: ${{ inputs.version == 'main' }}
        run: |
          git fetch --all
          git config --global user.email ${{ secrets.GITUSEREMAIL }}
          git config --global user.name ${{ secrets.GITUSERNAME }}
          mike deploy --push dev
          
      - name: Mike Released Version Snapshot
        if: ${{ inputs.version != 'main' }}
        run: |
          git fetch --all
          git config --global user.email ${{ secrets.GITUSEREMAIL }}
          git config --global user.name ${{ secrets.GITUSERNAME }}
          mike deploy --push ${{ inputs.version }}

      - name: Mike New Release Version Snapshot
        if: ${{ inputs.version != 'main' }}
        run: |
          git fetch --all
          git config --global user.email ${{ secrets.GITUSEREMAIL }}
          git config --global user.name ${{ secrets.GITUSERNAME }}
          mike deploy --push --update-aliases ${{ inputs.version }} latest
          mike set-default --push latest

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            matrixorigin/matrixorigin.io.cn:${{ inputs.version }}_${{ github.sha }}
            matrixorigin/matrixorigin.io.cn:latest     
